#title in header
title: "Hi hi hi ğŸ˜‡ ~"

#main info
#owner
owner: "I am enifmaii."
email: enifmaii@163.com
info: " "
#description
desc: " "

#menu
menu:
  Works: /Works
  About: /About

#index/main page max show posts (in number)
max_post: 5

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Changchun,China
placelink: https://en.wikipedia.org/wiki/Changchun
github: https://github.com/enifmaiii
#linkedin: https://linkedin.com/in/adisaktijrs
#twitter: https://twitter.com/adisaktijrs
#instagram: https://instagram.com/adisaktijrs
#stackoverflow: https://stackoverflow.com/story/tobiasreithmeier

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
